apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: ism-application-control-approved-registry
spec:
  validationFailureAction: Audit
---
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: ism-application-control-no-latest-tag
spec:
  validationFailureAction: Audit
---
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: ism-application-control-no-privileged
spec:
  validationFailureAction: Audit
---
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: ism-workload-hardening-security-context
spec:
  validationFailureAction: Audit
---
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: ism-workload-hardening-block-host-namespaces
spec:
  validationFailureAction: Audit
---
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: ism-workload-hardening-block-host-path
spec:
  validationFailureAction: Audit
---
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: ism-privileged-access-require-dedicated-sa
spec:
  validationFailureAction: Audit
---
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: ism-privileged-access-block-legacy-sa-tokens
spec:
  validationFailureAction: Audit
---
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: ism-privileged-access-block-cluster-admin-binding
spec:
  validationFailureAction: Audit
